version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 
     # test
	- run: |
	docker-compose -f docker-compose.unittests.yml run --rm unittests

     # build image
     - run: |         
         docker info
         docker build -t aspnetapp -f Dockerfile .

     # deploy the image
     - run: |         
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$HEROKU_APP_NAME/web
         docker push registry.heroku.com/$HEROKU_APP_NAME/web                
         
	- run:
name: Setup Heroku
command: |
chmod +x .circleci/setup-heroku.sh
.circleci/setup-heroku.sh
- run:
name: Deploy to Heroku
command: |
heroku container:release web --app $HEROKU_APP_NAME